### ISSUE TITLE
Docs should direct users with questions to use this issue queue

### ISSUE THREAD

**Issue by pdpinch** [mitodl/mit_lti_flask_sample#22]
Ferdi wrote in e-mail:
> Maybe add a friendly message in the readme file saying that our best support is the issue queue .

@pwilkins you are good with friendly, can you take care of this?

**Comment by pwilkins** [comment]
"Good with friendly"?  OK, I can own that.  :-)

**Comment by pwilkins** [comment]
Closed by PR#23
