### ISSUE TITLE
problems with python version and Heroku

### ISSUE THREAD

**Issue by njoliat** [mitodl/mit_lti_flask_sample#30]
hello,
when I try to deploy this example app to Heroku, I get an error about the python version; the version specified in runtime.txt seems to be too old:

"-----> Python app detected
 !     The latest version of Python 2 is python-2.7.14 (you are using python-2.7.8, which is unsupported).
 !     We recommend upgrading by specifying the latest version (python-2.7.14).
       Learn More: https://devcenter.heroku.com/articles/python-runtimes
-----> Installing python-2.7.8
 !     Requested runtime (python-2.7.8) is not available for this stack (heroku-16).
 !     Aborting.  More info: https://devcenter.heroku.com/articles/python-support
 !     Push rejected, failed to compile Python app.
 !     Push failed"

**Comment by pdpinch** [comment]
Thanks for letting us know. If you would like to open a PR to use a different Python version, we'd be happy to review and merge. 

The underlying python LTI library was recently updated to support Python 3.
