### ISSUE TITLE
Application crashes in Heroku

### ISSUE THREAD

**Issue by njoliat** [mitodl/mit_lti_flask_sample#32]
If I bump the Python and uWSGI versions (as [here](https://github.com/njoliat/mit_lti_flask_sample)), the app builds in Heroku, but crashes with an Application error when I try to run it.  The Heroku log displays the following error:

"2017-11-01T22:27:00.165110+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=POST path="/" host=lti-flask-sample-njoliat.herokuapp.com request_id=2a0c16de-2911-4b7a-adf8-e965e7abeaf5 fwd="71.174.35.149" dyno= connect= service= status=503 bytes= protocol=https"

**Comment by pdpinch** [comment]
@amir-qayyum-khan do you have any thoughts on this?

**Comment by kboots-mit** [comment]
This looks like a general and not very helpful heroku log response that is just saying that the app crashed, but not giving much other info. Seems like the sort of thing that others have faced when trying to get apps running. The following seems like a similar conversation to what this could become, https://github.com/mjhea0/flask-boilerplate/issues/14

Maybe something similar?

**Comment by njoliat** [comment]
hi Kyle,
apologies about the non-specific error message, and if I wasn't clear in how to reproduce the crash.  my code differs from the master branch here only in that I updated uWSGI in requirements.txt, (otherwise the app doesn't build on Heroku; see [PR](https://github.com/mitodl/mit_lti_flask_sample/pull/33)).  thus, to reproduce the crash:

1. go to [this branch](https://github.com/njoliat/mit_lti_flask_sample/tree/update-uwsgi) which updates the uWSGI version
2. deploy to Heroku using "deploy to Heroku" button, default everything
3. open the app

**Comment by njoliat** [comment]
@kboots-mit sorry I realized that I missed some better error messages from where the app crashes on startup, prior to the 503 thing I copied above; the logs for this can be found [here](https://pastebin.com/LkUw31yD).  I then added --preload to the Procfile (per [this possibly-relevant thread](https://stackoverflow.com/questions/28545608/problems-configuring-deployment-with-heroku-gunicorn-django)) and I got this longer error trace involving oauth2 and STRING_TYPES: https://pastebin.com/sL1c3gRz

**Comment by kboots-mit** [comment]
@amir-qayyum-khan any thoughts on this? Im a bit over my head with the python stuff here. Definitely looks like an issue with:
from oauth2 import STRING_TYPES
ImportError: cannot import name STRING_TYPES

**Comment by amir-qayyum-khan** [comment]
@njoliat can you test it with oauth2-1.9.0.post1, latest version?

**Comment by njoliat** [comment]
@amir-qayyum-khan this seems to solve the problem, thanks!  (when I view the LTI component via the course's edX page, I can see the menu with "Hello student.", "Start problem", etc.)

**Comment by njoliat** [comment]
(I created a PR for this here: https://github.com/mitodl/mit_lti_flask_sample/pull/34)
